name: Verify Action

on:
  pull_request:
  workflow_dispatch:

jobs:
  self_check:
    name: Run this Action
    runs-on: ubuntu-latest
    steps:
      - name: "Clone test project"
        uses: actions/checkout@v4
        with:
          repository: dstroot/nextjs-13-example

      - name: "Clone action"
        uses: actions/checkout@v4
        with:
          path: action
          clean: false

      - name: "Call action"
        id: action
        uses: ./action

      - name: Convert HTML to Markdown
        id: html2markdown
        if: always()
        uses: rknj/html2markdown@v0.1.0
        with:
          html-file: "codeclimate-report.html"
      - if: always()
        run: echo ${{ steps.html2markdown.outputs.markdown-content }} >> "$GITHUB_STEP_SUMMARY"

  enforce-all-checks:
    name: Enforce all checks
    needs: [self_check]
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: Enforce all checks
        uses: poseidon/wait-for-status-checks@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore: Enforce all checks