name: Verify Action

on:
  pull_request:
  workflow_dispatch:

jobs:
  self_check:
    name: Run this Action
    runs-on: ubuntu-latest
    steps:
      - name: "Clone test project"
        uses: actions/checkout@v4
        with:
          repository: dstroot/nextjs-13-example

      - name: "Clone action"
        uses: actions/checkout@v4
        with:
          path: action
          clean: false

      - name: "Call action"
        id: action
        uses: ./action

      - uses: buildingcash/json-to-markdown-table-action@v1
        if: always()
        id: table
        with:
          json_file_path: "codeclimate-report.json"
      - if: always()
        run: echo ${{ steps.table.outputs.table }} >> "$GITHUB_STEP_SUMMARY"

  enforce-all-checks:
    name: Enforce all checks
    needs: [self_check]
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - name: Enforce all checks
        uses: poseidon/wait-for-status-checks@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore: Enforce all checks